const countryInputFields = {
  countryDetailFields: [
    {
      name: 'countryId',
      label: 'Country Id',
      inputType: 'number',
      type: 'input',
      span: 4,
      title: 'Country Details',
      isRequired: true,
    },
    {
      name: 'sortname',
      label: 'Sort Name',
      type: 'input',
      span: 4,
      isRequired: true,
    },
    {
      name: 'name',
      label: 'Country Name',
      type: 'input',
      span: 6,
      isRequired: true,
    },
    {
      name: 'phoneCode',
      label: 'Phone Code',
      inputType: 'number',
      type: 'input',
      span: 3,
      isRequired: true,
    },
    {
      name: 'alpha3Code',
      label: 'Alpha 3 Code',
      type: 'input',
      span: 3,
      isRequired: true,
    },
    {
      name: 'alpha2Code',
      label: 'Alpha 2 Code',
      type: 'input',
      span: 3,
      isRequired: true,
    },
  ],
  currencyFields: [
    {
      name: 'currencyCode',
      label: 'Currency code',
      type: 'input',
      span: 6,
      title: 'Currency Details',
      isRequired: true,
    },
    {
      name: 'currencyName',
      label: 'Currency name',
      type: 'input',
      span: 6,
      isRequired: true,
    },
    {
      name: 'currencySymbol',
      label: 'Currency Symbol',
      type: 'input',
      span: 6,
      isRequired: true,
    },
    {
      name: 'currencyDisplayName',
      label: 'Currency display name',
      type: 'input',
      span: 6,
      isRequired: true,
    },
  ],
  countrySetting: [
    {
      name: 'isOnboardingApplicable',
      label: 'isOnboardingApplicable',
      type: 'switch',
      span: 3,
      title: 'Country Settings',
      isRequired: false,
    },
    {
      name: 'expressSupported',
      label: 'expressSupported',
      type: 'switch',
      span: 3,
      isRequired: false,
    },
    {
      name: 'expressEnabled',
      label: 'expressEnabled',
      type: 'switch',
      span: 3,
      isRequired: false,
    },
    {
      name: 'bankSupported',
      label: 'bankSupported',
      type: 'switch',
      span: 3,
      isRequired: false,
    },
    {
      name: 'isAliPaySupported',
      label: 'isAliPaySupported',
      type: 'switch',
      span: 3,
      isRequired: false,
    },
    {
      name: 'isStripeSupported',
      label: 'isStripeSupported',
      type: 'switch',
      span: 3,
      isRequired: false,
    },
    {
      name: 'isWeChatPaySupported',
      label: 'isWeChatPaySupported',
      type: 'switch',
      span: 3,
      isRequired: false,
    },
    {
      name: 'providerName',
      label: 'Providers Supported',
      type: 'select',
      options: [{ label: 'Stripe', value: 'stripe' }],
      span: 10,
      isRequired: false,
    },
    {
      name: 'cardChargeMessage',
      label: 'Card charge message',
      type: 'input',
      span: 10,
      isRequired: true,
    },
    {
      name: 'bankChargeMessage',
      label: 'Bank charge message',
      type: 'input',
      span: 10,
      isRequired: true,
    },
    {
      main: 'Message',
      subFields: [
        {
          name: 'messageHeading',
          label: 'Heading',
          type: 'input',
          span: 8,
          isRequired: true,
        },
        {
          name: 'messageBody',
          label: 'Body',
          type: 'input',
          span: 16,
          isRequired: true,
        },
        {
          name: 'messageHeading1',
          label: 'Heading',
          type: 'input',
          span: 8,
          isRequired: true,
        },
        {
          name: 'messageBody1',
          label: 'Body',
          type: 'input',
          span: 16,
          isRequired: true,
        },
      ],
    },
  ],
  publicStructureFields: [
    {
      title: 'Public Structure',
      main: 'Domestic',
      subFields: [
        {
          name: 'domesticTitle',
          label: 'Domestic Title',
          type: 'input',
          span: 12,
          isRequired: true,
        },
        {
          name: 'domesticFee',
          label: 'Domestic Fee',
          type: 'input',
          span: 12,
          isRequired: true,
        },
        {
          name: 'domesticTitle1',
          label: 'Domestic Title',
          type: 'input',
          span: 12,
          isRequired: true,
        },
        {
          name: 'domesticFee1',
          label: 'Domestic Fee',
          type: 'input',
          span: 12,
          isRequired: true,
        },
      ],
    },
    {
      main: 'International',
      subFields: [
        {
          name: 'internationalTitle',
          label: 'International Title',
          type: 'input',
          span: 12,
          isRequired: true,
        },
        {
          name: 'internationalFee',
          label: 'International Fee',
          type: 'input',
          span: 12,
          isRequired: true,
        },
      ],
    },
  ],
}

export default countryInputFields
